### ISSUE TITLE
Hangman-12 reduce parts of the image

### ISSUE THREAD

**Issue by mrmattmueller** [sw19-tug/SPbPU2019#69]
As a user I want to see that a piece of the hangman image is removed when I clock on a wrong letter so that I know I've been wrong

**Acceptance criteria:**
-) When the player guesses a letter wrong, one part is removed till all parts are gone

**Comment by ksemya** [comment]
When the player guesses a letter wrong, one part is shown, not removed
The end of the game is the full picture
