### ISSUE TITLE
Minesweeper-8 Set flags

### ISSUE THREAD

**Issue by mrmattmueller** [sw19-tug/SPbPU2019#8]
As a player I want to flag unopened cells so that I can make notes

**Acceptance Criteria:**
Right Click on closed cell puts mark as bomb

**Comment by rs1t** [comment]
After a discussion we decided to add another option to mark cells with a question mark, in case it is not clear whether cell has a bomb or not. The behavior is the same as with flags. We think it adds a good value for users and at the same time easy to implement. This great idea was proposed by @katunik
